#!/usr/bin/env bash
#
# Copy or link to prefered /bin directory
# To Run open a terminal and type `music_thingy` or use keyboard shortcuts to pass argument
# Examples "music_thingy https://ice2.somafm.com/secretagent-128-mp3" "music_thingy quit"  "/music_thingy shuffle"  "music_thingy favorites"



set -f
shopt -s nocasematch


OS_NAME=$(uname -s)
if [[ ${OS_NAME} == haiku ]]; then
		 notify="notify"
		 x=($(which ${notify%}))
		 [[ -n ${x[0]} ]] && notify="notify --title MusicThingy "
		 ConfigDir=${HOME}/config/settings/music_thingy
	     [[ ! -d $ConfigDir ]] && mkdir $ConfigDir
		 [[ ! -e $ConfigDir/favorites ]] && touch $ConfigDir/favorites
		 [[ ! -e $ConfigDir/config ]] && touch $ConfigDir/config
		 favs="$ConfigDir/favorites"
		 config="$ConfigDir/config"
		 if [[ ! -s $config ]];then
			    echo -e "show_alerts=0" > $config
			    echo -e "debug_disable_player=0" >> $config
		 fi
fi

if [[ ${OS_NAME} == linux ]]; then
		 notify="notify-send"
		 x=($(which ${notify%}))
		 [[ -n ${x[0]} ]] && notify="notify-send -a MusicThingy"
		 ConfigDir=${HOME}/.config/music_thingy
	 	 [[ ! -d $ConfigDir ]] && mkdir $ConfigDir
		 [[ ! -e $ConfigDir/favorites ]] && touch $ConfigDir/favorites
		 [[ ! -e $ConfigDir/config ]] && touch $ConfigDir/config
		 favs="$ConfigDir/favorites"
		 config="$ConfigDir/config"
		 if [[ ! -s $config ]];then
			    echo -e "show_alerts=1" > $config
			    echo -e "debug_disable_player=0" >> $config
		 fi

fi

source $config

if [[ ! $show_alerts ]];then
	echo -e "show_alerts=0" > $config
fi

if [[ ! $debug_disable_player ]];then
    echo -e "debug_disable_player=0" >> $config
fi

xcleanup_thingy(){
echo

[[ -e /tmp/music_thingy.pipe ]] && rm /tmp/music_thingy.pipe
[[ -e /tmp/music_thingy.pid ]] && kill -1 $(</tmp/music_thingy.pid) && rm /tmp/music_thingy.pid

}


vol() {
	  if [[ ${OS_NAME} == haiku ]]; then
  		  [[ $REPLY == + ]] && setvolume -i > /dev/null
  		  [[ $REPLY == - ]] && setvolume -d > /dev/null
  		  [[ $REPLY == m ]] && setvolume -m > /dev/null
  		  [[ $REPLY == u ]] && setvolume -u > /dev/null
  		  setvolume

elif [[ ${OS_NAME} == linux ]]; then
	for l in "$(amixer get Master)"
		do
			 l=${l// /_}
 	         l=${l/_[/ }
 		 	 l=${l/]_/ }
  		 	 l=($l)
  		 	 s="${l[5]}"

  		 		#Fix for raspberry pi *** maybe outdated
 		 		[[ ${#s} -gt 3 ]] && s="${l[6]}"

  		  soundlevel=${s//%/}
  		  inc_sound=$(($soundlevel + 1))
  		  dec_sound=$(($soundlevel - 1))

  		  [[ $REPLY == + ]] && amixer -q set Master $(($soundlevel + 1))% && s=$(($soundlevel + 1))%
  		  [[ $REPLY == - ]] && amixer -q set Master $(($soundlevel - 1))% && s=$(($soundlevel - 1))%
  		  [[ $REPLY == m ]] && amixer -q set Master mute && s=Muted
  		  [[ $REPLY == u ]] && amixer -q set Master unmute
  		  echo "Vol: ${s}"
	done
fi
}

## Default playlist.
## Playlist is saved in $config directory and music_thingy must be restarted to read modified playlist.

playlist="https://ice1.somafm.com/7soul-128-mp3#Seven Inch Soul - Vintage soul tracks from the original 45 RPM vinyl.
https://ice4.somafm.com/beatblender-128-mp3#Beat Blender - A late night blend of deep-house and downtempo chill.
https://ice4.somafm.com/bootliquor-128-mp3#Boot Liquor - Americana Roots music for Cowhands, Cowpokes and Cowtippers
https://ice6.somafm.com/brfm-128-mp3#Black Rock FM - From the Playa to the world, for the annual Burning Man festival.
https://ice6.somafm.com/cliqhop-128-mp3#cliqhop idm - Blips'n'beeps backed mostly w/beats. Intelligent Dance Music.
https://ice4.somafm.com/covers-128-mp3#Covers - Just covers. Songs you know by artists you don't. We've got you covered.
https://ice4.somafm.com/deepspaceone-128-mp3#Deep Space One - Deep ambient electronic, experimental and space music. For inner and outer space exploration.
https://ice2.somafm.com/defcon-128-mp3#DEF CON Radio - Music for Hacking. The DEF CON Year-Round Channel.
https://ice2.somafm.com/digitalis-128-mp3#Digitalis - Digitally affected analog rock to calm the agitated heart.
https://ice2.somafm.com/dubstep-128-mp3#Dub Step Beyond - Dubstep, Dub and Deep Bass. May damage speakers at high volume.
https://ice4.somafm.com/dronezone-128-mp3#Drone Zone - Served best chilled, safe with most medications. Atmospheric textures with minimal beats.
https://ice6.somafm.com/fluid-128-mp3#Fluid - Drown in the electronic sound of instrumental hiphop, future soul and liquid trap.
https://ice6.somafm.com/folkfwd-128-mp3#Folk Forward - Indie Folk, Alt-folk and the occasional folk classics.
https://ice4.somafm.com/groovesalad-128-mp3#Groove Salad - A nicely chilled plate of ambient/downtempo beats and grooves.
https://ice1.somafm.com/gsclassic-128-mp3#Groove Salad Classic - The classic (early 2000s) version of a nicely chilled plate of ambient/downtempo beats and grooves.
https://ice2.somafm.com/illstreet-128-mp3#Illinois Street Lounge - Classic bachelor pad, playful exotica and vintage music of tomorrow.
https://ice6.somafm.com/indiepop-128-mp3#Indie Pop Rocks! - New and classic favorite indie pop tracks.
https://ice6.somafm.com/live-128-mp3#SomaFM Live - Special Live Events and rebroadcasts of past live events.
https://ice6.somafm.com/lush-128-mp3#Lush - Sensuous and mellow female vocals, many with an electronic influence.
https://ice1.somafm.com/metal-128-mp3#Metal Detector - From black to doom, prog to sludge, thrash to post, stoner to crossover, punk to industrial.
https://ice4.somafm.com/missioncontrol-128-mp3#Mission Control - Celebrating NASA and Space Explorers everywhere.
https://ice1.somafm.com/n5md-128-mp3#n5MD Radio Emotional Experiments in Music: Ambient, modern composition, post-rock, & experimental electronic music.
https://ice6.somafm.com/poptron-128-mp3#PopTron - Electropop and indie dance rock with sparkle and pop.
https://ice6.somafm.com/u80s-128-mp3#Underground 80s - Early 80s UK Synthpop and a bit of New Wave.
https://ice4.somafm.com/reggae-128-mp3#Heavyweight Reggae - Reggae, Ska, Rocksteady classic and deep tracks.
https://ice6.somafm.com/scanner-128-mp3#SF Police Scanner - San Francisco Public Safety Scanner Feed.
https://ice2.somafm.com/secretagent-128-mp3#Secret Agent - The soundtrack for your stylish, mysterious, dangerous life. For Spies and PIs too!
https://ice6.somafm.com/seventies-128-mp3#Left Coast 70s - Mellow album rock from the Seventies. Yacht not required.
https://ice4.somafm.com/sf1033-128-mp3#SF 10-33 - Ambient music mixed with the sounds of San Francisco public safety radio traffic.
https://ice6.somafm.com/sonicuniverse-128-mp3#Sonic Universe - Transcending the world of jazz with eclectic, avant-garde takes on tradition.
https://ice1.somafm.com/spacestation-128-mp3#Space Station - Soma Tune in, turn on, space out. Spaced-out ambient and mid-tempo electronica.
https://ice2.somafm.com/specials-128-mp3#Department Store Christmas Holiday Elevator Music from a more innocent time. (Specials).
https://ice4.somafm.com/suburbsofgoa-128-mp3#Suburbs of Goa - Desi-influenced Asian world beats and beyond.
https://ice1.somafm.com/synphaera-128-mp3#Synphaera Radio - Featuring the music from an independent record label focused on modern electronic ambient and space music.
https://ice4.somafm.com/reggae-128-mp3#The Trip - Progressive house / trance. Tip top tunes.
https://ice6.somafm.com/thistle-128-mp3#ThistleRadio - Exploring music from Celtic roots and branches
https://ice1.somafm.com/vaporwaves-128-mp3#Vaporwaves - All Vaporwave. All the time."

if [[ ${OS_NAME} == haiku ]]; then
	 [[ ! -e $ConfigDir/playlist ]] && echo -n "${playlist[*]}" > $ConfigDir/playlist
	  playlist="$(< $ConfigDir/playlist)"

elif [[ ${OS_NAME} == linux ]]; then
	 [[ ! -e $ConfigDir/playlist ]] && echo -n "${playlist[*]}" > $ConfigDir/playlist
	  playlist="$(< $ConfigDir/playlist)"
fi

mapfile playlist <<< $playlist

# Added option to pass argument given to command line.
# Arguments accepted are quit, shuffle, favorites, or custom stream URL
# Works good for things like KDE-connect and keyboard shortcuts to play music_thingy in the backend.
# Examples "music_thingy https://ice2.somafm.com/secretagent-128-mp3" "music_thingy quit"  "music_thingy shuffle"  "music_thingy favorites"
if [[ $1 ]];then
        if [[ ${1} != quit && ${1} != shuffle && ${1} != favorites && ${1} != del_favorite  && ${1} != add_favorite && ${1} != inc_vol && ${1} != dec_vol ]];then
        xcleanup_thingy
        echo $BASHPID > /tmp/music_thingy.pid
        playlist="$1"
        mapfile playlist <<< $playlist
        fi

        if [[ ${1} == favorites ]]; then
     	   xcleanup_thingy
     	   echo $BASHPID > /tmp/music_thingy.pid
     	   REPLY=f
        fi

	    if [[ ${1} == inc_vol ]]; then
        	 REPLY=+
        	 vol
        	 exit 0
	  	fi

	    if [[ ${1} == dec_vol ]]; then
        	 REPLY=-
        	 vol
        	 exit 0
	  	fi

	    if [[ ${1} == add_favorite ]]; then
 			tmp=$(</tmp/music_thingy.info) ### Repeat delete cmds so no duplicate entries
			foo=$(<$favs)
			echo "${foo//"$tmp"}" | sed '/^$/d' > $favs
			fav=$(</tmp/music_thingy.info)
			echo $fav >> $favs
			if [[ $show_alerts == 1 ]]; then
			 $notify "${fav//\\n */}


Added to favorites."
			fi

   		 exit 0
		fi

	 	if [[ ${1} == del_favorite ]]; then
			tmp=$(</tmp/music_thingy.info)
			foo=$(<$favs)
			echo "${foo//"$tmp"}" | sed '/^$/d' > $favs
			if  [[ ! -s $ConfigDir/favorites && $show_alerts == 1 ]];then
			 $notify "

Playlist is empty."
			 exit 0
			fi
			fav=$(</tmp/music_thingy.info)

			if [[ $show_alerts == 1 ]]; then
			 $notify "${fav//\\n */}


Deleted from favorites."
			exit 0
			fi

			fav=$(</tmp/music_thingy.info)

         exit 0
		fi

	if [[ ${1} == shuffle ]]; then
       	   xcleanup_thingy
     	   echo $BASHPID > /tmp/music_thingy.pid
     	   REPLY=s
	fi

	if [[ ${1} == quit ]]; then
        	xcleanup_thingy
			exit 0
	fi
fi






start() {
try() {
        nu="0-$((${#playlist[*]}-1))"
		shuffle="$(shuf -i $nu -n 1)"
		pl="${playlist[$shuffle]}"
		tr=(${pl//#/\/ })
		tr=${tr[0]}
        xcleanup_thingy

       (echo $BASHPID > /tmp/music_thingy.pid
       source $config
	   exec -a music_thingy $player --quiet ${tr}) > /tmp/music_thingy.pipe &
		url="${pl//,/\\n *}"
		url="${url//\ -\ /\\n * }"
		url="${url//.\ /\\n * }"
		url=(${url//#/\\n * })
		echo ${url[*]} > /tmp/music_thingy.info
}
[[ ! -e /tmp/music_thingy.pid ]] && try

if [[ -s /tmp/music_thingy.info ]];then
title="$(</tmp/music_thingy.info)"
title="${title/\\n\ \*/\\n   *}"
title="${title//\\n\ \*/,}"
	echo -e "   * $title \n   * Total Playlists ${#playlist[*]}   "

fi

[[ -e /tmp/music_thingy.pipe ]] && exec {FD}</tmp/music_thingy.pipe
if [[ -e /tmp/music_thingy.pipe ]];then


while read  -u "$FD" info; do



info=${info//icy-title:/Title:}
title="$(echo -e "${BLUE}${info}" | sed s/^/\ \ \ *\ / | grep -m 1 "Title" | tac)"
export title="$title"

done
fi
echo "$title"

exec {FD}>&-
echo -e "${BLUE}${info}   * $(vol)"
echo -e "${BLUE}${info}   * $(date)"




	echo -e "\\n\\n\\n\\n\\n${ORANGE}Interactive Music Thingy${BLUE}~ $:-) "


}

main() {

tput -S <<!
clear
setab 0
cup 10
smso
bold
!
echo -e "${BLACK}                   Interactive Music Thingy               \n             https://github.com/ablyssx74/                \n   \
        [S]huffle/[Q]uit   Vol +/-   [H]elp Menu       \n       \n     \n   \n \n${BLUE}"

tput rmso


start


}

while true
	do


		 player="mpv"
		 BLUE="$(tput setaf 12)"
		 RED="$(tput setaf 9)"
		 GREEN="$(tput setaf 46)"
		 NORM="$(tput setaf 15)"
		 ORANGE="$(tput setaf 9)"
		 BLACK="$(tput setaf 234)"
		 REPLY=${REPLY,,}
		 #pids="$(ps | grep music_thing)"
		 x=($(which ${player%}))
		if [[ ${OS_NAME} == haiku ]]; then
				 [[ -z ${x[0]} ]] && echo -e "\\n${ORANGE}${player}${RED} not installed. ${BLUE}Please install it with pkgman install mpv. :-)\\n" && break
        elif [[ ${OS_NAME} == linux ]]; then
				 [[ -z ${x[0]} ]] && echo -e "\\n${ORANGE}${player}${RED} not installed. ${BLUE}Please install it with your OS package manager.  :-)\\n" && break
		fi
		 if [[ ${REPLY} == q ]];then
			 echo -e "\\n\\n${BLUE}bye!\\n\\n"
		 	 xcleanup_thingy
		      break
		  else
			while true
				do read -n 1 -r
				echo "$(main "$@")"
				done<<<$(echo)

		  	#read -s -r -p "$(main "$@")" -n 1


		 fi
	done
