#!/usr/bin/env bash
#
# Copy or link to prefered /bin directory
# To Run open a terminal and type `music_thingy` or use keyboard shortcuts to pass argument
# Examples "music_thingy https://ice2.somafm.com/secretagent-128-mp3" "music_thingy quit"  "/music_thingy shuffle"  "music_thingy favorites"



set -f
shopt -s nocasematch

OS_NAME=$(uname -s)
if [[ ${OS_NAME} == haiku ]]; then
		 notify="notify --title MusicThingy "
		 ConfigDir=${HOME}/config/settings/music_thingy
	     [[ ! -d $ConfigDir ]] && mkdir $ConfigDir
		 [[ ! -e $ConfigDir/favorites ]] && touch $ConfigDir/favorites
		 [[ ! -e $ConfigDir/config ]] && touch $ConfigDir/config
		 favs="$ConfigDir/favorites"
		 config="$ConfigDir/config"
		 if [[ ! -s $config ]];then
				declare -A _config=( [show_alerts]="\"1\"" [debug_disable_player]="\"1\"" [title]="\"1\"" )
					for value in "${!_config[@]}"
						do
							echo "$value=${_config[$value]}" >> $config
						done
			    #echo -e "show_alerts=0" > $config
			    #echo -e "debug_disable_player=0" >> $config
		 fi
fi

if [[ ${OS_NAME} == linux ]]; then
		 notify="notify-send -a MusicThingy"
		 ConfigDir=${HOME}/.config/music_thingy
	 	 [[ ! -d $ConfigDir ]] && mkdir -p $ConfigDir
		 [[ ! -e $ConfigDir/favorites ]] && touch $ConfigDir/favorites
		 [[ ! -e $ConfigDir/config ]] && touch $ConfigDir/config
		 favs="$ConfigDir/favorites"
		 config="$ConfigDir/config"
		 if [[ ! -s $config ]];then
				declare -A _config=( [show_alerts]="\"1\"" [debug_disable_player]="\"1\"" [title]="\"1\"" )
					for value in "${!_config[@]}"
						do
							echo "$value=${_config[$value]}" >> $config
						done
			    #echo -e "show_alerts=1" > $config
			    #echo -e "debug_disable_player=0" >> $config
		 fi

fi



source $config
if [[ ! $_config ]];then
	rm $config
	declare -A _config=([show_alerts]="\"$show_alerts\"" [debug_disable_player]="\"$debug_disable_player\"" [title]="\"$title\"")
		for value in "${!_config[@]}"
			do
				echo "$value=${_config[$value]}" >> $config
			done
	source $config
fi

if [[ ! $show_alerts ]];then
	echo -e "show_alerts=0" > $config
fi

if [[ ! $debug_disable_player ]];then
    echo -e "debug_disable_player=0" >> $config
fi

cleanup_thingy(){
mapfile pids <<< $pids
	if [[ ${#pids[*]} -gt 1 ]];then
		pid0="${pids[0]}"
		pid0=(${pid0})
		kill -1 "${pid0[1]}"
		pid1="${pids[1]}"
		pid1=(${pid1})
		kill -1 "${pid1[1]}"
       fi
}

xcleanup_thingy(){
echo
#exec 3>&-
#cleanup_thingy

[[ -e /tmp/music_thingy.pid ]] && kill -1 $(</tmp/music_thingy.pid) && rm /tmp/music_thingy.pid

}


vol() {
	  if [[ ${OS_NAME} == haiku ]]; then
  		  [[ $REPLY == + ]] && setvolume -i > /dev/null
  		  [[ $REPLY == - ]] && setvolume -d > /dev/null
  		  [[ $REPLY == m ]] && setvolume -m > /dev/null
  		  [[ $REPLY == u ]] && setvolume -u > /dev/null
  		  setvolume

elif [[ ${OS_NAME} == linux ]]; then
	for l in "$(amixer get Master)"
		do
			 l=${l// /_}
 	         l=${l/_[/ }
 		 	 l=${l/]_/ }
  		 	 l=($l)
  		 	 s="${l[5]}"

  		 		#Fix for raspberry pi *** maybe outdated
 		 		[[ ${#s} -gt 3 ]] && s="${l[6]}"

  		  soundlevel=${s//%/}
  		  inc_sound=$(($soundlevel + 1))
  		  dec_sound=$(($soundlevel - 1))

  		  [[ $REPLY == + ]] && amixer -q set Master $(($soundlevel + 1))% && s=$(($soundlevel + 1))%
  		  [[ $REPLY == - ]] && amixer -q set Master $(($soundlevel - 1))% && s=$(($soundlevel - 1))%
  		  [[ $REPLY == m ]] && amixer -q set Master mute && s=Muted
  		  [[ $REPLY == u ]] && amixer -q set Master unmute
  		  echo "${s}"
	done
fi
}

## Default playlist.
## Playlist is saved in $config directory and music_thingy must be restarted to read modified playlist.

playlist="https://ice1.somafm.com/7soul-128-mp3#Seven Inch Soul - Vintage soul tracks from the original 45 RPM vinyl.
https://ice4.somafm.com/beatblender-128-mp3#Beat Blender - A late night blend of deep-house and downtempo chill.
https://ice4.somafm.com/bootliquor-128-mp3#Boot Liquor - Americana Roots music for Cowhands, Cowpokes and Cowtippers
https://ice6.somafm.com/brfm-128-mp3#Black Rock FM - From the Playa to the world, for the annual Burning Man festival.
https://ice6.somafm.com/cliqhop-128-mp3#cliqhop idm - Blips'n'beeps backed mostly w/beats. Intelligent Dance Music.
https://ice4.somafm.com/covers-128-mp3#Covers - Just covers. Songs you know by artists you don't. We've got you covered.
https://ice4.somafm.com/deepspaceone-128-mp3#Deep Space One - Deep ambient electronic, experimental and space music. For inner and outer space exploration.
https://ice2.somafm.com/defcon-128-mp3#DEF CON Radio - Music for Hacking. The DEF CON Year-Round Channel.
https://ice2.somafm.com/digitalis-128-mp3#Digitalis - Digitally affected analog rock to calm the agitated heart.
https://ice2.somafm.com/dubstep-128-mp3#Dub Step Beyond - Dubstep, Dub and Deep Bass. May damage speakers at high volume.
https://ice4.somafm.com/dronezone-128-mp3#Drone Zone - Served best chilled, safe with most medications. Atmospheric textures with minimal beats.
https://ice6.somafm.com/fluid-128-mp3#Fluid - Drown in the electronic sound of instrumental hiphop, future soul and liquid trap.
https://ice6.somafm.com/folkfwd-128-mp3#Folk Forward - Indie Folk, Alt-folk and the occasional folk classics.
https://ice4.somafm.com/groovesalad-128-mp3#Groove Salad - A nicely chilled plate of ambient/downtempo beats and grooves.
https://ice1.somafm.com/gsclassic-128-mp3#Groove Salad Classic - The classic (early 2000s) version of a nicely chilled plate of ambient/downtempo beats and grooves.
https://ice2.somafm.com/illstreet-128-mp3#Illinois Street Lounge - Classic bachelor pad, playful exotica and vintage music of tomorrow.
https://ice6.somafm.com/indiepop-128-mp3#Indie Pop Rocks! - New and classic favorite indie pop tracks.
https://ice6.somafm.com/live-128-mp3#SomaFM Live - Special Live Events and rebroadcasts of past live events.
https://ice6.somafm.com/lush-128-mp3#Lush - Sensuous and mellow female vocals, many with an electronic influence.
https://ice1.somafm.com/metal-128-mp3#Metal Detector - From black to doom, prog to sludge, thrash to post, stoner to crossover, punk to industrial.
https://ice4.somafm.com/missioncontrol-128-mp3#Mission Control - Celebrating NASA and Space Explorers everywhere.
https://ice1.somafm.com/n5md-128-mp3#n5MD Radio Emotional Experiments in Music: Ambient, modern composition, post-rock, & experimental electronic music.
https://ice6.somafm.com/poptron-128-mp3#PopTron - Electropop and indie dance rock with sparkle and pop.
https://ice6.somafm.com/u80s-128-mp3#Underground 80s - Early 80s UK Synthpop and a bit of New Wave.
https://ice4.somafm.com/reggae-128-mp3#Heavyweight Reggae - Reggae, Ska, Rocksteady classic and deep tracks.
https://ice6.somafm.com/scanner-128-mp3#SF Police Scanner - San Francisco Public Safety Scanner Feed.
https://ice2.somafm.com/secretagent-128-mp3#Secret Agent - The soundtrack for your stylish, mysterious, dangerous life. For Spies and PIs too!
https://ice6.somafm.com/seventies-128-mp3#Left Coast 70s - Mellow album rock from the Seventies. Yacht not required.
https://ice4.somafm.com/sf1033-128-mp3#SF 10-33 - Ambient music mixed with the sounds of San Francisco public safety radio traffic.
https://ice6.somafm.com/sonicuniverse-128-mp3#Sonic Universe - Transcending the world of jazz with eclectic, avant-garde takes on tradition.
https://ice1.somafm.com/spacestation-128-mp3#Space Station - Soma Tune in, turn on, space out. Spaced-out ambient and mid-tempo electronica.
https://ice2.somafm.com/specials-128-mp3#Department Store Christmas Holiday Elevator Music from a more innocent time. (Specials).
https://ice4.somafm.com/suburbsofgoa-128-mp3#Suburbs of Goa - Desi-influenced Asian world beats and beyond.
https://ice1.somafm.com/synphaera-128-mp3#Synphaera Radio - Featuring the music from an independent record label focused on modern electronic ambient and space music.
https://ice4.somafm.com/reggae-128-mp3#The Trip - Progressive house / trance. Tip top tunes.
https://ice6.somafm.com/thistle-128-mp3#ThistleRadio - Exploring music from Celtic roots and branches
https://ice1.somafm.com/vaporwaves-128-mp3#Vaporwaves - All Vaporwave. All the time."

if [[ ${OS_NAME} == haiku ]]; then
	 [[ ! -e $ConfigDir/playlist ]] && echo -n "${playlist[*]}" > $ConfigDir/playlist
	  playlist="$(< $ConfigDir/playlist)"

elif [[ ${OS_NAME} == linux ]]; then
	 [[ ! -e $ConfigDir/playlist ]] && echo -n "${playlist[*]}" > $ConfigDir/playlist
	  playlist="$(< $ConfigDir/playlist)"
fi

mapfile playlist <<< $playlist

# Added option to pass argument given to command line.
# Arguments accepted are quit, shuffle, favorites, or custom stream URL
# Works good for things like KDE-connect and keyboard shortcuts to play music_thingy in the backend.
# Examples "music_thingy https://ice2.somafm.com/secretagent-128-mp3" "music_thingy quit"  "music_thingy shuffle"  "music_thingy favorites"
if [[ $1 ]];then
        if [[ ${1} != quit && ${1} != shuffle && ${1} != favorites && ${1} != del_favorite  && ${1} != add_favorite && ${1} != inc_vol && ${1} != dec_vol ]];then
        xcleanup_thingy
        echo $BASHPID > /tmp/music_thingy.pid
        playlist="$1"
        mapfile playlist <<< $playlist
        fi

        if [[ ${1} == favorites ]]; then
     	   xcleanup_thingy
     	   echo $BASHPID > /tmp/music_thingy.pid
     	   REPLY=f
        fi

	    if [[ ${1} == inc_vol ]]; then
        	 REPLY=+
        	 vol
        	 exit 0
	  	fi

	    if [[ ${1} == dec_vol ]]; then
        	 REPLY=-
        	 vol
        	 exit 0
	  	fi

	    if [[ ${1} == add_favorite ]]; then
 			tmp=$(</tmp/music_thingy.info) ### Repeat delete cmds so no duplicate entries
			foo=$(<$favs)
			echo "${foo//"$tmp"}" | sed '/^$/d' > $favs
			fav=$(</tmp/music_thingy.info)
			echo $fav >> $favs
			if [[ $show_alerts == 1 ]]; then
			 $notify "${fav//\\n */}


Added to favorites."
			fi

   		 exit 0
		fi

	 	if [[ ${1} == del_favorite ]]; then
			tmp=$(</tmp/music_thingy.info)
			foo=$(<$favs)
			echo "${foo//"$tmp"}" | sed '/^$/d' > $favs
			if  [[ ! -s $ConfigDir/favorites && $show_alerts == 1 ]];then
			 $notify "

Playlist is empty."
			 exit 0
			fi
			fav=$(</tmp/music_thingy.info)

			if [[ $show_alerts == 1 ]]; then
			 $notify "${fav//\\n */}


Deleted from favorites."
			exit 0
			fi

			fav=$(</tmp/music_thingy.info)

         exit 0
		fi

	if [[ ${1} == shuffle ]]; then
       	   xcleanup_thingy
     	   echo $BASHPID > /tmp/music_thingy.pid
     	   REPLY=s
	fi

	if [[ ${1} == quit ]]; then
        	xcleanup_thingy
			exit 0
	fi
fi

#configs=($(<$ConfigDir/config))

startplaying(){

main(){
mapfile x <$ConfigDir/config
var=0
v=$((${#x[*]} - 1))
#while [[ $var -le $v ]]
#	do


#		name="${x[$var]}"
#		match="="
#		name="${name%$match*}"
#		#echo "$var: ${name}"





#		if [[ $REPLY == $var ]];then

#			for value in "${!_config[@]}"
#				do
#					fc=${_config[$value]//\"}

					#####Show_alerts
#					if [[ $REPLY == ${fc} ]];then
#						if [[ $show_alerts == ${fc} ]];then
#						   rm $config
#						   declare -A _config=( [show_alerts]="\"$REPLY\"" [debug_disable_player]="\"$debug_disable_player\"" [title]="\"$title\"" )
#							for value in "${!_config[@]}"
#								do
#									echo "$value=${_config[$value]}" >> $config
#								done
#								source $config
#								echo "showalerts $show_alerts"
#								return
#						fi

#					fi

#					if [[ $REPLY != ${fc} ]];then
#						if [[ $show_alerts  == ${fc} ]];then
#						   rm $config
#						   declare -A _config=( [show_alerts]="\"$REPLY\"" [debug_disable_player]="\"$debug_disable_player\"" [title]="\"$title\"" )
#							for value in "${!_config[@]}"
#								do
#									echo "$value=${_config[$value]}" >> $config
#								done
#								source $config
#								echo "showalerts $show_alerts"
#						fi

#					fi
					#####/Show_alerts

#				done

#		fi

#		((var++))


#	done
#return




while [[ $var -le $v ]]
	do

		#echo $var:${x[$var]}

		if [[ $REPLY == $var ]];then
		echo -e "  ${RED}<Config>\\n\\n ${BLUE} * Press 0..9${RED}"
		x=${x//\"/}
		a="$var:${x[$var]}"
		name="${x[$var]}"
		c="${#name}"
		((c--)) && ((c--))
		value=${name[*]:$c}
		(( 0 == value )) && cv=1
		(( 1 == value )) && cv=0
		n1=${name%??}$value
		n2=${name%??}$cv

#		echo "x $x"
#		echo "a $a"
#		echo "var $var"
#		echo "name $name"
#		echo "c $c"
#		echo "value $value"

#		echo "n1 $n1"
#		echo "n2 $n2"

	    #echo Saving\ $n1\to $n2
	    #i=0
	    #ii=$((${#x[*]} - 1))
		#while [[ $i -le $ii ]]
		# do
		#	echo ""Press:$i to change status of ${x[$i]}""
		#	((i++))
		#done


			mapfile x2 <$ConfigDir/config
			var2=0
			v2=$((${#x2[*]} - 1))

				while [[ $var2 -le $v2 ]]
					do
						try=${x2[$var2]}
						try=${try//\"/}
						arr+=(${try/$n1/$n2})
						((var2++))

					done

					try2="${arr[*]}"
					try2="${try2//\"/}"
					echo -e "${try2// /\\n}" > $ConfigDir/config

					#echo -e "${try2}" | sed s/$/\"\\n/ > $ConfigDir/config
					source $config

					mapfile x3 <$ConfigDir/config
						    i=0
							ii=$((${#x3[*]} - 1))
							while [[ $i -le $ii ]]
								do
								echo -e ""        ${BLUE}     * ${RED}Status: ${BLUE}${x3[$i]}${RED}""
							((i++))
						done

						echo -e "\\n${RED}  </Config>\\n${BLUE}\\n\\n\\n\\n\\n"
						footer
			exit 0
		fi

		((var++))


done

title="$(</tmp/music_thingy.info)"
title="${title/\\n\ \*/\\n   *}"
title="${title//\\n\ \*/,}"
	echo -e "   * $title \n   * Total Playlists ${#playlist[*]}   "
}
xfooter(){
	[[ $REPLY == f && -s $favs ]] && echo "${RED}Shuffling Favorites${BLUE} (-:"
	[[ $REPLY == f && ! -s $favs ]] && echo "${RED}Favorites is empty. Press \"s\" then \"a\" to add to favorites.${BLUE} (-:"
	[[ $REPLY == s ]] && echo "${RED}Shuffling All${BLUE} (-:"
	[[ $REPLY == a ]] && echo "${RED}Added to favorites. Press \"F\" to shuffle favorites. Press \"L\" to list playlist.${BLUE} (-:"
	[[ $REPLY == d ]] && echo "${RED}Deleted from favorites. Press \"F\" to shuffle favorites. Press \"L\" to list playlist.${BLUE} (-:"

}
footer(){
	echo -e "\\n\\n${ORANGE}Interactive Music Thingy${BLUE}~ $:-) $(xfooter) "
}
if [[ $REPLY == a ]];then
    if [[ -s $favs ]];then ## make sure favorits is not empty
		tmp=$(</tmp/music_thingy.info) ### Repeat the delete cmds so no duplicate entries
		foo=$(<$favs)
		echo "${foo//"$tmp"}" | sed '/^$/d' > $favs
	fi
	fav=$(</tmp/music_thingy.info)
	echo $fav >> $favs

fi
if [[ $REPLY == l ]];then
	echo -e "${BLUE}  ${RED}<Favorites>\\n${BLUE}\\n$(<$favs)"
	echo -e "\\n${BLUE}  ${RED}</Favorites>\\n${BLUE}"
	footer
	return
fi
if [[ $REPLY == d ]];then
	tmp=$(</tmp/music_thingy.info)
	foo=$(<$favs)
	echo "${foo//"$tmp"}" | sed '/^$/d' > $favs
fi


if [[ ${REPLY} == h ]];then
	echo -e "${BLUE}  ${RED}<Help>\\n"
	echo -e "${BLUE} * ${RED} [a]  Add to favorites"
	echo -e "${BLUE} * ${RED} [d]  Delete from favorites"
	echo -e "${BLUE} * ${RED} [c]  Config Manager"
	echo -e "${BLUE} * ${RED} [f]  Shuffle favorites"
	echo -e "${BLUE} * ${RED} [l]  List favorites"
	echo -e "${BLUE} * ${RED} [s]  Shuffle all"
	echo -e "${BLUE} * ${RED} [q]  Quit"
	echo -e "${BLUE} * ${RED} [m]  Mute"
	echo -e "${BLUE} * ${RED} [u]  Unmute"
	echo -e "${BLUE} * ${RED} [+]  Vol up"
	echo -e "${BLUE} * ${RED} [-]  Vol down"
	echo -e "${BLUE} * ${RED} [h]  Help menu"
	echo -e "${BLUE}  ${RED}\\n  </Help>\\n${BLUE}"
	footer
 return
fi
if [[ ${REPLY} == c ]];then
	echo -e "  ${RED}<Config>\\n\\n ${BLUE} * Press 0..9${RED}"
	mapfile x <$ConfigDir/config
		i=0
	    ii=$((${#x[*]} - 1))
		while [[ $i -le $ii ]]
		 do
			echo -ne "${BLUE}  * ${RED}Status: ${BLUE}${x[$i]}"
			((i++))
		done
	echo -en "${BLUE}  ${RED}\\n  </Config>\\n${BLUE}\\n\\n\\n\\n\\n\\n"

	footer
 return
fi

if [[ $REPLY == f ]];then
		 if [[ -s $favs ]];then
		mapfile playlist < $favs
		nu="0-$((${#playlist[*]}-1))"
		shuffle="$(shuf -i $nu -n 1)"
		pl="${playlist[$shuffle]}"
		tr=(${pl//\\n/\/ })
		tr=${tr[0]}
		xcleanup_thingy
       (echo $BASHPID > /tmp/music_thingy.pid
       source $config
       [[ $debug_disable_player == 1 ]] && return 0
       exec -a music_thingy $player --quiet ${tr}) >&3 &


        url="${pl//,/\\n *}"
		url="${url//\ -\ /\\n * }"
		url="${url//.\ /\\n * }"
		url=(${url//#/\\n * })
		echo ${url[*]} > /tmp/music_thingy.info
		fi
fi

if [[ $REPLY == s || ! $REPLY ]];then
        nu="0-$((${#playlist[*]}-1))"
		shuffle="$(shuf -i $nu -n 1)"
		pl="${playlist[$shuffle]}"
		tr=(${pl//#/\/ })
		tr=${tr[0]}
        xcleanup_thingy

       (echo $BASHPID > /tmp/music_thingy.pid
       source $config
       [[ $debug_disable_player == 1 ]] && return 0

       exec -a music_thingy $player --quiet ${tr}) >&3 &

        url="${pl//,/\\n *}"
		url="${url//\ -\ /\\n * }"
		url="${url//.\ /\\n * }"
		url=(${url//#/\\n * })
		echo ${url[*]} > /tmp/music_thingy.info
fi

main "$@"
echo -e "${BLUE}${info}   * Vol: $(vol)"

if [[ $REPLY != - && $REPLY != + && $REPLY != a && $REPLY != d && $REPLY != h && $REPLY != c && $REPLY != l && ! $REPLY =~ ^[0-9]$  ]];then

while read -t 3 -u 3 info
do
#mapfile line <<< "$info"
#	for line in "$info"
#		do

			#line=($info)
#			i=0
#			ii=${#line[*]}
#				while [[ $i -le $ii ]]
#				do
#					echo "$ii=\"${line[$i]}\""
#					((i++))
#				done
#		done

#info="${info//AO:\ \[openal\]\ / ${BLUE}  * }"
#info="${info//\[openal\]\ / ${BLUE}  * }"
#info=${info//File\ tags:/$(vol) }
#info=${info//Exiting...\ \(Quit\)/}
#info=${info//-aid=1/}
#info=${info//\(+\)\ / ${BLUE} * }
#info=${info//\ icy-title:/Title:}
# | sed s/^/\ \ \ *\ /
if [[ $info == icy-title* ]];then
title="${info//icy-title:/}"
#export test="x $title"
echo -e "${BLUE}   * Title:$title"
#[[ -n $title ]] && echo "meta_title=\"$title\"" > ./reply.txt

fi

done | pv -rN "
$(printf '\033[H\033[2J') ${BLUE} 

 		 Interactive Music Thingy



         Loading data, please wait..."
fi
exec 3<&-

echo -e "\\n\\n\\n\\n\\n\\n\\n"
footer "$@"

}

main() {
tput -S <<!
clear
cup 10
smso
bold
!
printf "\033[30m\033[0m\n"
echo -e "${BLUE}                   Interactive Music Thingy               \n                 https://github.com/ablyssx74                \n   \
        [S]huffle/[Q]uit   Vol +/-   [H]elp Menu       \n       \n     \n   \n \n"

tput rmso

PIPE=$(mktemp -u)
mkfifo "$PIPE"
exec 3<>"$PIPE"
rm $PIPE



startplaying "$@"



}

while true
	do
		 player="mpv"
		 BLUE="$(tput setaf 12)"
		 RED="$(tput setaf 9)"
		 GREEN="$(tput setaf 46)"
		 NORM="$(tput setaf 15)"
		 ORANGE="$(tput setaf 9)"
		 BLACK="$(tput setaf 234)"
		 testplayer=($(which ${player%}))
		 pv="pv"
		 testpv=($(which ${pv%}))
		 if [[ ${OS_NAME} == haiku ]]; then
			notify="notify"
			notify=($(which ${notify%}))
				[[ -z ${notify[0]} ]] &&  echo -e "\\n${ORANGE}notify${RED} not installed. ${BLUE}Please install it with your package manager. :-)\\n" && break

		elif [[ ${OS_NAME} == linux ]]; then
			notify="notify-send"
			notify=($(which ${notify%}))
				[[ -z ${notify[0]} ]] && echo -e "\\n${ORANGE}notify-send${RED} not installed. ${BLUE}Please install it with your package manager. :-)\\n" && break

		fi
		[[ -z ${testplayer[0]} ]] && echo -e "\\n${ORANGE}${player}${RED} not installed. ${BLUE}Please install it with your package manager.  :-)\\n" && break
		[[ -z ${testpv[0]} ]] && echo -e "\\n${ORANGE}pv${RED} not installed. ${BLUE}Please install it with your package manager. :-)\\n" && break

		if [[ ${REPLY} == q ]];then
			 echo -e "\\n\\n${BLUE}bye!\\n\\n"
		 	 xcleanup_thingy
		      break
		  else
		  	 read -s -p "$(main "$@")" -n 1

		fi
	done
