#!/usr/bin/env bash
#
# Copy or link to prefered /bin directory
# To Run open a terminal and type `music_thingy` or use keyboard shortcuts to pass argument
# Examples "music_thingy https://ice2.somafm.com/secretagent-128-mp3" "music_thingy quit"  "/music_thingy shuffle"  "music_thingy favorites"



set -f
shopt -s nocasematch
[[ ! -d /tmp/music_thingy ]] && mkdir /tmp/music_thingy

OS_NAME=$(uname -s)
if [[ ! $config ]];then
	if [[ ${OS_NAME} == haiku ]]; then
			notify="notify --title MusicThingy "
			ConfigDir=${HOME}/config/settings/music_thingy
			[[ ! -d $ConfigDir ]] && mkdir $ConfigDir
			[[ ! -e $ConfigDir/favorites ]] && touch $ConfigDir/favorites
			[[ ! -e $ConfigDir/config ]] && touch $ConfigDir/config
			favs="$ConfigDir/favorites"
			config="$ConfigDir/config"
			if [[ ! -s $config ]];then
					declare -A _config=( [notify_active]="\"1\"" [debug_disable_player]="\"0\"" [buffer_wait_time]="\"3\"" [test]="\"4\"" [show_all_meta_data]="\"0\"")
						for value in "${!_config[@]}"
							do
								echo "$value=${_config[$value]}" >> $config
							done
			fi
	fi

	if [[ ${OS_NAME} == linux ]]; then
			notify="notify-send -a MusicThingy"
			ConfigDir=${HOME}/.config/music_thingy
			[[ ! -d $ConfigDir ]] && mkdir -p $ConfigDir
			[[ ! -e $ConfigDir/favorites ]] && touch $ConfigDir/favorites
			[[ ! -e $ConfigDir/config ]] && touch $ConfigDir/config
			favs="$ConfigDir/favorites"
			config="$ConfigDir/config"
			if [[ ! -s $config ]];then
					declare -A _config=( [notify_active]="\"1\"" [debug_disable_player]="\"0\"" [buffer_wait_time]="\"3\"" [show_all_meta_data]="\"0\"" [use_pactl_to_get_volume]="\"1\"")
						for value in "${!_config[@]}"
							do
								echo "$value=${_config[$value]}" >> $config
							done
			fi

	fi
fi

source $config

cleanup(){
echo
[[ -e /tmp/music_thingy/music_thingy.info ]] && mv /tmp/music_thingy/music_thingy.info /tmp/music_thingy/music_thingy.previous.info
[[ -e /tmp/music_thingy/music_thingy.title ]] && rm /tmp/music_thingy/music_thingy.title
[[ -e /tmp/music_thingy/music_thingy.name ]] && rm /tmp/music_thingy/music_thingy.name
[[ -e /tmp/music_thingy/music_thingy.genre ]] && rm /tmp/music_thingy/music_thingy.genre
[[ -e /tmp/music_thingy/music_thingy.pid ]] && kill -1 $(</tmp/music_thingy/music_thingy.pid) && rm /tmp/music_thingy/music_thingy.pid
}

trap 'cleanup' EXIT

vol() {
source $config
	  if [[ ${OS_NAME} == haiku ]]; then
  		  [[ $REPLY == + ]] && setvolume -i > /dev/null
  		  [[ $REPLY == - ]] && setvolume -d > /dev/null
  		  [[ $REPLY == m ]] && setvolume -m > /dev/null
  		  [[ $REPLY == u ]] && setvolume -u > /dev/null
  		  echo -e "   * $(setvolume)"


elif [[ ${OS_NAME} == linux ]]; then

	if [[ $use_pactl_to_get_volume == 1 ]];then

  		  [[ -e /tmp/music_thingy/music_thingy.title ]] && foo="$(</tmp/music_thingy/music_thingy.title)"
  		  foo="${foo[0]}"
  		  foo2="$(pactl list sink-inputs | grep -B 25 "media.name = \"${foo} - mpv\"")"
  		  mapfile x <<< "$foo2"
  		  x="${x[0]}"
  		  y="${x[10]}"
  		  y=($y)
  		  v="${y[4]}"
  		  sinkID="${x//Sink\ Input\ \#/}"
		  soundlevel=${v//%/}
  		  inc_sound=$(($soundlevel + 1))
  		  dec_sound=$(($soundlevel - 1))

  		  [[ $REPLY == + ]] && pactl set-sink-input-volume $sinkID $(($soundlevel + 1))% && s=$(($soundlevel + 1))%
  		  [[ $REPLY == - ]] && pactl set-sink-input-volume $sinkID $(($soundlevel - 1))% && s=$(($soundlevel - 1))%

  		  [[ -n $soundlevel ]] && echo -n "${BLUE}${info}   * Vol ${soundlevel}%"


	fi

	if [[ $use_pactl_to_get_volume == 0 ]];then

	for l in "$(amixer get Master)"
		do
			 l=${l// /_}
 	         l=${l/_[/ }
 		 	 l=${l/]_/ }
  		 	 l=($l)
  		 	 s="${l[6]}"

  		 		#Fix for raspberry pi *** maybe outdated
 		 		[[ ${#s} -gt 3 ]] && s="${l[6]}"

  		  soundlevel=${s//%/}
  		  inc_sound=$(($soundlevel + 1))
  		  dec_sound=$(($soundlevel - 1))

  		  [[ $REPLY == + ]] && amixer -q set Master $(($soundlevel + 1))% && s=$(($soundlevel + 1))%
  		  [[ $REPLY == - ]] && amixer -q set Master $(($soundlevel - 1))% && s=$(($soundlevel - 1))%
  		  [[ $REPLY == m ]] && amixer -q set Master mute
  		  [[ $REPLY == u ]] && amixer -q set Master unmute
		  [[ ${l[7]} == "[off]" ]] && s=Muted
  		  echo -n "${BLUE}${info}   * Vol ${s}"
	done
	fi
fi
}

getplaylist() {
	_curl="$(curl -s -H 'Accept: application/json' https://somafm.com/channels.json | jq  -rj '.. | select(.description? and .listeners and .id? or .url?) | "_listeners_=\(.listeners) _fid_ \(.id) _fdes_ \(.description) _furl_ \(.url)"')"
	_curl="${_curl// _furl_ null_fid_ null _fdes_ null _furl_ /\\n}" 
	_curl="${_curl//_fid_ null _fdes_ null _furl_ /\\n}"
	_curl="${_curl//_listeners_=null/}"
	_curl="${_curl//_furl_ null/}"		 
	_curl="${_curl//_fid_ /\\n}"
	_curl="${_curl// _fdes_ / - }" 
	_curl="${_curl//_listeners_=/\\nlisteners=}"
	ids="$(echo -en "${_curl}" | grep -e ' - ')" 
	listeners="$(echo -en "${_curl}" | grep -e 'listeners=')" 
	urls="$(echo -en "${_curl}" | grep -e '130.pls')"
	
	mapfile url <<< $urls
	mapfile id <<< $ids
	mapfile listener <<< $listeners
	i=0
	while [[ $i -le ${#id[@]} ]]
		do
			id_url="$(echo -en ${url[$i]}\#${id[$i]}\ #${listener[$i]})"
			id_url="${id_url// #/#}"
			[[ ${id_url} =~ https ]] && echo -en "$id_url\\n"
			((i++))
		done
}


mapfile playlist <<< $(getplaylist)


# Added option to pass argument given to command line.
# Arguments accepted are quit, shuffle, favorites, or custom stream URL
# Works great with keyboard shortcuts or KDE-connect to play music_thingy in the backend.
# Examples "music_thingy https://ice2.somafm.com/secretagent-128-mp3" "music_thingy quit"  "music_thingy shuffle"  "music_thingy favorites"
if [[ $1 ]];then
        if [[ ${1} != quit && ${1} != shuffle && ${1} != favorites && ${1} != del_favorite  && ${1} != add_favorite && ${1} != inc_vol && ${1} != dec_vol ]];then
        	cleanup
        	echo $BASHPID > /tmp/music_thingy/music_thingy.pid
        	playlist="$1"
        	mapfile playlist <<< $playlist
        fi

        if [[ ${1} == favorites ]]; then
     	   cleanup
     	   echo $BASHPID > /tmp/music_thingy/music_thingy.pid
     	   REPLY=f
        fi

	    if [[ ${1} == inc_vol ]]; then
        	 REPLY=+
        	 vol
        	 exit 0
	  	fi

	    if [[ ${1} == dec_vol ]]; then
        	 REPLY=-
        	 vol
        	 exit 0
	  	fi

	    if [[ ${1} == add_favorite ]]; then
 			 tmp=$(</tmp/music_thingy/music_thingy.info) ### Repeat delete cmds so no duplicate entries
			 foo=$(<$favs)
			 echo "${foo//"$tmp"}" | sed '/^$/d' > $favs
			 fav=$(</tmp/music_thingy/music_thingy.info)
			 echo $fav >> $favs
			 if [[ $notify_active == 1 ]]; then
			   $notify "${fav//\\n */}


Added to favorites."
			 fi

   		 exit 0
		fi

	 	if [[ ${1} == del_favorite ]]; then
			tmp=$(</tmp/music_thingy/music_thingy.info)
			foo=$(<$favs)
			echo "${foo//"$tmp"}" | sed '/^$/d' > $favs
			if  [[ ! -s $ConfigDir/favorites && $notify_active == 1 ]];then
			 $notify "

Playlist is empty."
			 exit 0
			fi
			fav=$(</tmp/music_thingy/music_thingy.info)

			if [[ $notify_active == 1 ]]; then
			 $notify "${fav//\\n */}


Deleted from favorites."
			exit 0
			fi
			fav=$(</tmp/music_thingy/music_thingy.info)
         	exit 0
		fi

	if [[ ${1} == shuffle ]]; then
       	   cleanup
     	   echo $BASHPID > /tmp/music_thingy/music_thingy.pid
     	   REPLY=s
	fi

	if [[ ${1} == quit ]]; then
        	cleanup
			exit 0
	fi
fi

startplaying(){

header(){
mapfile x <$ConfigDir/config
var=0
v=$((${#x[*]} - 1))

while [[ $var -le $v ]]
	do
		if [[ $REPLY == $var ]];then
			echo -e "  ${RED}<Config>\\n ${BLUE} * Press 0..9${RED}"
			x=${x//\"/}
			a="$var:${x[$var]}"
			name="${x[$var]}"
			c="${#name}"
			((c--)) && ((c--))
			value=${name[*]:$c}
			(( 0 == value )) && cv=1
			(( 1 == value )) && cv=0
			(( 3 == value )) && cv=3
			(( 4 == value )) && cv=4
		
			n1=${name%??}$value
			n2=${name%??}$cv

			mapfile x2 <$ConfigDir/config
			var2=0
			v2=$((${#x2[*]} - 1))

				while [[ $var2 -le $v2 ]]
					do
						try=${x2[$var2]}
						try=${try//\"/}
						arr+=(${try/$n1/$n2})
						((var2++))

					done

					try2="${arr[*]}"
					try2="${try2//\"/}"
					echo -e "${try2// /\\n}" > $ConfigDir/config

					source $config

					mapfile x3 <$ConfigDir/config
						    i=0
							ii=$((${#x3[*]} - 1))
							while [[ $i -le $ii ]]
								do
								echo -e ""        ${BLUE}     * ${RED}Status: ${BLUE}${x3[$i]}${RED}""
							((i++))
						done

						echo -e "${RED}  </Config>${BLUE}"
						footer
			exit 0
		fi

		((var++))
done
}

footer(){
tput cup $(tput lines) 0
echo -e "\\n${ORANGE}Interactive Music Thingy${BLUE}~ $:-)"
}

if [[ ${REPLY} == h ]];then
	echo -e "${BLUE}  ${RED}<Help>"
	echo -e "${BLUE} * ${RED} [s] ${BLUE} Shuffle All"
	echo -e "${BLUE} * ${RED} [f] ${BLUE} Shuffle Favorites"
	echo -e "${BLUE} * ${RED} [a] ${BLUE} Add Favorite"
	echo -e "${BLUE} * ${RED} [d] ${BLUE} Delete Favorite"
	echo -e "${BLUE} * ${RED} [p] ${BLUE} Previous Stream"
	echo -e "${BLUE} * ${RED} [r] ${BLUE} Refresh Current Stream"
	echo -e "${BLUE} * ${RED} [l] ${BLUE} List Favorites"
	echo -e "${BLUE} * ${RED} [t] ${BLUE} Show Available Channels"
	echo -e "${BLUE} * ${RED} [m] ${BLUE} Mute"
	echo -e "${BLUE} * ${RED} [u] ${BLUE} Unmute"
	echo -e "${BLUE} * ${RED} [+] ${BLUE} Vol Up"
	echo -e "${BLUE} * ${RED} [-] ${BLUE} Vol Down"
	echo -e "${BLUE} * ${RED} [h] ${BLUE} Help Menu"
	echo -e "${BLUE} * ${RED} [c] ${BLUE} Config Manager"
	echo -e "${BLUE} * ${RED} [q] ${BLUE} Quit"
	echo -e "${BLUE}  ${RED}</Help>${BLUE}"
	footer
 return
fi

if [[ $REPLY == a ]];then
    if [[ -s $favs ]];then ## make sure favorits is not empty
		tmp=$(</tmp/music_thingy/music_thingy.info) ### Repeat the delete cmds so no duplicate entries
		foo=$(<$favs)
		echo "${foo//"$tmp"}" | sed '/^$/d' > $favs
	fi
	shortmsg="Adding to Favorites, please wait"
	fav=$(</tmp/music_thingy/music_thingy.info)
	echo $fav >> $favs
	REPLY=r

fi
if [[ $REPLY == l ]];then
	echo -e "${BLUE}  ${RED}<Favorites>\\n${BLUE}$(<$favs)"
	echo -e "${BLUE}  ${RED}</Favorites>${BLUE}"
	footer
	return
fi
if [[ $REPLY == d ]];then
	tmp=$(</tmp/music_thingy/music_thingy.info)
	foo=$(<$favs)
	[[ ! -s $favs ]] && shortmsg="Favorites is empty."
	[[ -s $favs ]] && shortmsg="Deleting Favorite, please wait"
	echo "${foo//"$tmp"}" | sed '/^$/d' > $favs
	REPLY=r
fi

if [[ ${REPLY} == c ]];then
	echo -e "  ${RED}<Config>\\n ${BLUE} * Press 0..9${RED}"
	mapfile x <$ConfigDir/config
		i=0
	    ii=$((${#x[*]} - 1))
		while [[ $i -le $ii ]]
		 do
			echo -ne "${BLUE}  * ${RED}Status: ${BLUE}${x[$i]}"
			((i++))
		done
	echo -e "${RED}  </Config>${BLUE}"

	footer
 return
fi

if [[ $REPLY == t ]];then
getplaylist
return
fi

if [[ $REPLY == f ]];then
		 if [[ -s $favs ]];then
			mapfile playlist < $favs
			nu="0-$((${#playlist[*]}-1))"
			shuffle="$(shuf -i $nu -n 1)"
			pl="${playlist[$shuffle]}"
			tr=(${pl})
			tr=${tr[0]}
			tr="$(getplaylist | grep -e ${tr})"
			tr=(${pl//#/ })		
			tr=${tr[0]}	
			listeners="${tr: -14}"
			listeners="${listeners//[^0-9]/}"	
			shortmsg="Shuffling Favorites, please wait"	
			player_start
       		info_out
		fi
fi
if [[ $REPLY == p ]];then
		if [[ -s /tmp/music_thingy/music_thingy.previous.info ]];then
			mapfile previous < /tmp/music_thingy/music_thingy.previous.info
			nu="0-$((${#previous[*]}-1))"
			shuffle="$(shuf -i $nu -n 1)"
			pl="${previous[$shuffle]}"
			tr=(${pl})
			tr=${tr[0]}
			tr="$(getplaylist | grep -e ${tr})"
			tr=(${pl//#/ })		
			tr=${tr[0]}	
			listeners="${tr: -14}"
			listeners="${listeners//[^0-9]/}"	
			shortmsg="Loading Previous, please wait"
			player_start
       		info_out
	    fi
fi

if [[ $REPLY == r ]];then
		if [[ -s /tmp/music_thingy/music_thingy.info ]];then
			mapfile refresh < /tmp/music_thingy/music_thingy.info
			nu="0-$((${#refresh[*]}-1))"
			shuffle="$(shuf -i $nu -n 1)"
			pl="${refresh[$shuffle]}"
			tr=(${pl})
			tr=${tr[0]}
			tr="$(getplaylist | grep -e ${tr})"
			tr=(${pl//#/ })		
			tr=${tr[0]}	
			listeners="${tr: -14}"
			listeners="${listeners//[^0-9]/}"
			shortmsg="Refreshing Playlist, please wait"
			player_start
			info_out
		fi
fi

if [[ $REPLY == s ]];then
        nu="0-$((${#playlist[*]}-1))"
		shuffle="$(shuf -i $nu -n 1)"
		pl="${playlist[$shuffle]}"
		tr=(${pl})
		tr=(${pl//#/ })		
		tr=${tr[0]}		
		listeners="${pl: -14}"
		listeners="${listeners//[^0-9]/}"
		shortmsg="Shuffling Playlist, please wait"
		player_start
		info_out
fi

header

msg() {

echo "$(printf '\033[H\033[2J')$(logo)



$(tput cup 11 9)${shortmsg}
$(footer)"

 }


if [[ -n $REPLY && ! $REPLY =~ [^[:alnum:][:space:]]  && ! $REPLY =~ ^[0-9]$ ]];then

	while read -t 3 -u ${fd} info
		do
			if [[ $info == icy-title* ]];then
					[[ -e /tmp/music_thingy/music_thingy.title ]] && rm /tmp/music_thingy/music_thingy.title
					title="${info//icy-title:/}"
					echo $title > /tmp/music_thingy/music_thingy.title					
			fi

			if [[ $info =~ icy-name: ]];then
					[[ -e /tmp/music_thingy/music_thingy.name ]] && rm /tmp/music_thingy/music_thingy.name
					name="${info/icy-name:/}"
					echo $name > /tmp/music_thingy/music_thingy.name				
			fi

			if [[ $info =~ icy-genre: ]];then
					[[ -e /tmp/music_thingy/music_thingy.genre ]] && rm /tmp/music_thingy/music_thingy.genre
					genre="${info/icy-genre:/}"
					echo $genre > /tmp/music_thingy/music_thingy.genre				
			fi


		done | pv -rN "$(msg)$(tput cup 10 43)" 
fi

exec {fd}<&-

[[ -e /tmp/music_thingy/music_thingy.title ]] &&  echo -e "   * $(</tmp/music_thingy/music_thingy.title)"
[[ -e /tmp/music_thingy/music_thingy.name  ]] &&  echo -e "   * $(</tmp/music_thingy/music_thingy.name)"
[[ -e /tmp/music_thingy/music_thingy.genre  ]] &&  echo -e "   * $(</tmp/music_thingy/music_thingy.genre)"
[[ $listeners  ]] &&  echo -e "   * Listeners: $listeners / Channels in Playlist: ${#playlist[*]}"

[[ ! $REPLY ]] &&  echo -e "   * Press \"s\" to start"

echo -e "$(vol)"

footer
}


main() {

	info_out() {
		echo "${tr}" > /tmp/music_thingy/music_thingy.info
	}
	player_start() {
        cleanup
        (echo $BASHPID > /tmp/music_thingy/music_thingy.pid
        source $config
        [[ $debug_disable_player == 1 ]] && return 0
        exec -a music_thingy $player --quiet --display-tags=\* ${tr}) >&${fd} &
	    info_out
	}

tput -S <<!
clear
civis
!

printf "\033[30m\033[0m"
logo() {
echo "$(tput cup 5 19)${BLUE}Interactive Music Thingy"
echo "$(tput cup 6 17)${BLUE}https://github.com/ablyssx74"
echo "$(tput cup 7 11)${BLUE}[S]huffle/[Q]uit   Vol +/-   [H]elp Menu"
}
logo


data=$(mktemp -u)
mkfifo "$data"
exec {fd}<>"$data"
rm $data

echo "$(tput cup 10 0)${BLUE}"
startplaying
}

while true
	do
		 player="mpv"
		 BLUE="$(tput setaf 12)"
		 RED="$(tput setaf 9)"
		 GREEN="$(tput setaf 46)"
		 NORM="$(tput setaf 15)"
		 ORANGE="$(tput setaf 9)"
		 BLACK="$(tput setaf 234)"
		 testplayer=($(which ${player%}))
		 pv="pv"
		 testpv=($(which ${pv%}))
		 if [[ ${OS_NAME} == haiku ]]; then
			notify="notify"
			notify=($(which ${notify%}))
				[[ -z ${notify[0]} ]] &&  echo -e "${ORANGE}notify${RED} not installed. ${BLUE}Please install it with your package manager. :-)" && break

		elif [[ ${OS_NAME} == linux ]]; then
			notify="notify-send"
			notify=($(which ${notify%}))
				[[ -z ${notify[0]} ]] && echo -e "${ORANGE}notify-send${RED} not installed. ${BLUE}Please install it with your package manager. :-)" && break

		fi
		[[ -z ${testplayer[0]} ]] && echo -e "${ORANGE}${player}${RED} not installed. ${BLUE}Please install it with your package manager.  :-)" && break
		[[ -z ${testpv[0]} ]] && echo -e "${ORANGE}pv${RED} not installed. ${BLUE}Please install it with your package manager. :-)" && break

		if [[ ${REPLY} == q ]];then
			    tput cup $(tput lines) 0
				echo -e "${ORANGE}Interactive Music Thingy${BLUE}~ $:-) Logging out! "
		 	    cleanup
		        break
		  else
		  	 read -s -p "$(main)" -n 1

		fi
	done
